esconju abanicar               ip  | egrep "yo" >>  car.ip.yo
esconju abarcar                ip  | egrep "yo" >>  car.ip.yo
esconju abarracar              ip  | egrep "yo" >>  car.ip.yo
esconju abarrancar             ip  | egrep "yo" >>  car.ip.yo
esconju abayuncar              ip  | egrep "yo" >>  car.ip.yo
esconju abdicar                ip  | egrep "yo" >>  car.ip.yo
esconju abellacar              ip  | egrep "yo" >>  car.ip.yo
esconju abocar                 ip  | egrep "yo" >>  car.ip.yo
esconju abracar                ip  | egrep "yo" >>  car.ip.yo
esconju abroncar               ip  | egrep "yo" >>  car.ip.yo
esconju acercar                ip  | egrep "yo" >>  car.ip.yo
esconju acetificar             ip  | egrep "yo" >>  car.ip.yo
esconju achacar                ip  | egrep "yo" >>  car.ip.yo
esconju achicar                ip  | egrep "yo" >>  car.ip.yo
esconju achocar                ip  | egrep "yo" >>  car.ip.yo
esconju achurruscar            ip  | egrep "yo" >>  car.ip.yo
esconju acidificar             ip  | egrep "yo" >>  car.ip.yo
esconju aclocar                ip  | egrep "yo" >>  car.ip.yo
esconju acullicar              ip  | egrep "yo" >>  car.ip.yo
esconju adanlascar             ip  | egrep "yo" >>  car.ip.yo
esconju adjudicar              ip  | egrep "yo" >>  car.ip.yo
esconju afincar                ip  | egrep "yo" >>  car.ip.yo
esconju ahincar                ip  | egrep "yo" >>  car.ip.yo
esconju ahocicar               ip  | egrep "yo" >>  car.ip.yo
esconju ahorcar                ip  | egrep "yo" >>  car.ip.yo
esconju ahuecar                ip  | egrep "yo" >>  car.ip.yo
esconju alambicar              ip  | egrep "yo" >>  car.ip.yo
esconju alocar                 ip  | egrep "yo" >>  car.ip.yo
esconju altercar               ip  | egrep "yo" >>  car.ip.yo
esconju amorcar                ip  | egrep "yo" >>  car.ip.yo
esconju amoscar                ip  | egrep "yo" >>  car.ip.yo
esconju amplificar             ip  | egrep "yo" >>  car.ip.yo
esconju amurcar                ip  | egrep "yo" >>  car.ip.yo
esconju apalancar              ip  | egrep "yo" >>  car.ip.yo
esconju aparcar                ip  | egrep "yo" >>  car.ip.yo
esconju apañuscar              ip  | egrep "yo" >>  car.ip.yo
esconju apencar                ip  | egrep "yo" >>  car.ip.yo
esconju apeñuscar              ip  | egrep "yo" >>  car.ip.yo
esconju aplacar                ip  | egrep "yo" >>  car.ip.yo
esconju aplicar                ip  | egrep "yo" >>  car.ip.yo
esconju apocar                 ip  | egrep "yo" >>  car.ip.yo
esconju apontocar              ip  | egrep "yo" >>  car.ip.yo
esconju aporcar                ip  | egrep "yo" >>  car.ip.yo
esconju apriscar               ip  | egrep "yo" >>  car.ip.yo
esconju arcar                  ip  | egrep "yo" >>  car.ip.yo
esconju arencar                ip  | egrep "yo" >>  car.ip.yo
esconju aricar                 ip  | egrep "yo" >>  car.ip.yo
esconju arrancar               ip  | egrep "yo" >>  car.ip.yo
esconju arrejacar              ip  | egrep "yo" >>  car.ip.yo
esconju arriscar               ip  | egrep "yo" >>  car.ip.yo
esconju arrusticar             ip  | egrep "yo" >>  car.ip.yo
esconju asacar                 ip  | egrep "yo" >>  car.ip.yo
esconju asobarcar              ip  | egrep "yo" >>  car.ip.yo
esconju asurcar                ip  | egrep "yo" >>  car.ip.yo
esconju atacar                 ip  | egrep "yo" >>  car.ip.yo
esconju atascar                ip  | egrep "yo" >>  car.ip.yo
esconju atrabancar             ip  | egrep "yo" >>  car.ip.yo
esconju atracar                ip  | egrep "yo" >>  car.ip.yo
esconju atrancar               ip  | egrep "yo" >>  car.ip.yo
esconju atrincar               ip  | egrep "yo" >>  car.ip.yo
esconju aurificar              ip  | egrep "yo" >>  car.ip.yo
esconju autenticar             ip  | egrep "yo" >>  car.ip.yo
esconju autentificar           ip  | egrep "yo" >>  car.ip.yo
esconju avocar                 ip  | egrep "yo" >>  car.ip.yo
esconju azocar                 ip  | egrep "yo" >>  car.ip.yo
esconju bancar                 ip  | egrep "yo" >>  car.ip.yo
esconju batucar                ip  | egrep "yo" >>  car.ip.yo
esconju bazucar                ip  | egrep "yo" >>  car.ip.yo
esconju beatificar             ip  | egrep "yo" >>  car.ip.yo
esconju becar                  ip  | egrep "yo" >>  car.ip.yo
esconju besucar                ip  | egrep "yo" >>  car.ip.yo
esconju bisecar                ip  | egrep "yo" >>  car.ip.yo
esconju bizcar                 ip  | egrep "yo" >>  car.ip.yo
esconju blincar                ip  | egrep "yo" >>  car.ip.yo
esconju bonificar              ip  | egrep "yo" >>  car.ip.yo
esconju brescar                ip  | egrep "yo" >>  car.ip.yo
esconju brincar                ip  | egrep "yo" >>  car.ip.yo
esconju briscar                ip  | egrep "yo" >>  car.ip.yo
esconju buscar                 ip  | egrep "yo" >>  car.ip.yo
esconju caducar                ip  | egrep "yo" >>  car.ip.yo
esconju calcar                 ip  | egrep "yo" >>  car.ip.yo
esconju calcificar             ip  | egrep "yo" >>  car.ip.yo
esconju calificar              ip  | egrep "yo" >>  car.ip.yo
esconju cascar                 ip  | egrep "yo" >>  car.ip.yo
esconju caseificar             ip  | egrep "yo" >>  car.ip.yo
esconju causticar              ip  | egrep "yo" >>  car.ip.yo
esconju centuplicar            ip  | egrep "yo" >>  car.ip.yo
esconju cercar                 ip  | egrep "yo" >>  car.ip.yo
esconju certificar             ip  | egrep "yo" >>  car.ip.yo
esconju chamuscar              ip  | egrep "yo" >>  car.ip.yo
esconju chancar                ip  | egrep "yo" >>  car.ip.yo
esconju chapecar               ip  | egrep "yo" >>  car.ip.yo
esconju chascar                ip  | egrep "yo" >>  car.ip.yo
esconju checar                 ip  | egrep "yo" >>  car.ip.yo
esconju chicar                 ip  | egrep "yo" >>  car.ip.yo
esconju chiscar                ip  | egrep "yo" >>  car.ip.yo
esconju chocar                 ip  | egrep "yo" >>  car.ip.yo
esconju churruscar             ip  | egrep "yo" >>  car.ip.yo
esconju ciscar                 ip  | egrep "yo" >>  car.ip.yo
esconju clarificar             ip  | egrep "yo" >>  car.ip.yo
esconju clasificar             ip  | egrep "yo" >>  car.ip.yo
esconju claudicar              ip  | egrep "yo" >>  car.ip.yo
esconju clocar                 ip  | egrep "yo" >>  car.ip.yo
esconju cocar                  ip  | egrep "yo" >>  car.ip.yo
esconju codificar              ip  | egrep "yo" >>  car.ip.yo
esconju colocar                ip  | egrep "yo" >>  car.ip.yo
esconju comarcar               ip  | egrep "yo" >>  car.ip.yo
esconju comiscar               ip  | egrep "yo" >>  car.ip.yo
esconju complicar              ip  | egrep "yo" >>  car.ip.yo
esconju comunicar              ip  | egrep "yo" >>  car.ip.yo
esconju conculcar              ip  | egrep "yo" >>  car.ip.yo
esconju confiscar              ip  | egrep "yo" >>  car.ip.yo
esconju contraatacar           ip  | egrep "yo" >>  car.ip.yo
esconju contraindicar          ip  | egrep "yo" >>  car.ip.yo
esconju contramarcar           ip  | egrep "yo" >>  car.ip.yo
esconju convocar               ip  | egrep "yo" >>  car.ip.yo
esconju corporificar           ip  | egrep "yo" >>  car.ip.yo
esconju coruscar               ip  | egrep "yo" >>  car.ip.yo
esconju criticar               ip  | egrep "yo" >>  car.ip.yo
esconju crucificar             ip  | egrep "yo" >>  car.ip.yo
esconju cuacar                 ip  | egrep "yo" >>  car.ip.yo
esconju cuadriplicar           ip  | egrep "yo" >>  car.ip.yo
esconju cuadruplicar           ip  | egrep "yo" >>  car.ip.yo
esconju cualificar             ip  | egrep "yo" >>  car.ip.yo
esconju cuantificar            ip  | egrep "yo" >>  car.ip.yo
esconju cubicar                ip  | egrep "yo" >>  car.ip.yo
esconju cucar                  ip  | egrep "yo" >>  car.ip.yo
esconju curruscar              ip  | egrep "yo" >>  car.ip.yo
esconju damnificar             ip  | egrep "yo" >>  car.ip.yo
esconju decalcificar           ip  | egrep "yo" >>  car.ip.yo
esconju decuplicar             ip  | egrep "yo" >>  car.ip.yo
esconju dedicar                ip  | egrep "yo" >>  car.ip.yo
esconju defalcar               ip  | egrep "yo" >>  car.ip.yo
esconju defecar                ip  | egrep "yo" >>  car.ip.yo
esconju deificar               ip  | egrep "yo" >>  car.ip.yo
esconju demarcar               ip  | egrep "yo" >>  car.ip.yo
esconju densificar             ip  | egrep "yo" >>  car.ip.yo
esconju deprecar               ip  | egrep "yo" >>  car.ip.yo
esconju derrocar               ip  | egrep "yo" >>  car.ip.yo
esconju desabarrancar          ip  | egrep "yo" >>  car.ip.yo
esconju desaplicar             ip  | egrep "yo" >>  car.ip.yo
esconju desaporcar             ip  | egrep "yo" >>  car.ip.yo
esconju desatacar              ip  | egrep "yo" >>  car.ip.yo
esconju desatancar             ip  | egrep "yo" >>  car.ip.yo
esconju desatascar             ip  | egrep "yo" >>  car.ip.yo
esconju desatracar             ip  | egrep "yo" >>  car.ip.yo
esconju desatrancar            ip  | egrep "yo" >>  car.ip.yo
esconju desbancar              ip  | egrep "yo" >>  car.ip.yo
esconju desbocar               ip  | egrep "yo" >>  car.ip.yo
esconju descalcar              ip  | egrep "yo" >>  car.ip.yo
esconju descalcificar          ip  | egrep "yo" >>  car.ip.yo
esconju descalificar           ip  | egrep "yo" >>  car.ip.yo
esconju descascar              ip  | egrep "yo" >>  car.ip.yo
esconju descercar              ip  | egrep "yo" >>  car.ip.yo
esconju desclasificar          ip  | egrep "yo" >>  car.ip.yo
esconju descocar               ip  | egrep "yo" >>  car.ip.yo
esconju descolocar             ip  | egrep "yo" >>  car.ip.yo
esconju desconvocar            ip  | egrep "yo" >>  car.ip.yo
esconju descrucificar          ip  | egrep "yo" >>  car.ip.yo
esconju desecar                ip  | egrep "yo" >>  car.ip.yo
esconju desedificar            ip  | egrep "yo" >>  car.ip.yo
esconju deseducar              ip  | egrep "yo" >>  car.ip.yo
esconju desembarcar            ip  | egrep "yo" >>  car.ip.yo
esconju desembarrancar         ip  | egrep "yo" >>  car.ip.yo
esconju desembocar             ip  | egrep "yo" >>  car.ip.yo
esconju desempacar             ip  | egrep "yo" >>  car.ip.yo
esconju desencalcar            ip  | egrep "yo" >>  car.ip.yo
esconju desenfocar             ip  | egrep "yo" >>  car.ip.yo
esconju desenroscar            ip  | egrep "yo" >>  car.ip.yo
esconju desestancar            ip  | egrep "yo" >>  car.ip.yo
esconju desfalcar              ip  | egrep "yo" >>  car.ip.yo
esconju desflecar              ip  | egrep "yo" >>  car.ip.yo
esconju desflocar              ip  | egrep "yo" >>  car.ip.yo
esconju deshincar              ip  | egrep "yo" >>  car.ip.yo
esconju deshipotecar           ip  | egrep "yo" >>  car.ip.yo
esconju desintoxicar           ip  | egrep "yo" >>  car.ip.yo
esconju desmitificar           ip  | egrep "yo" >>  car.ip.yo
esconju desmultiplicar         ip  | egrep "yo" >>  car.ip.yo
esconju desnucar               ip  | egrep "yo" >>  car.ip.yo
esconju despancar              ip  | egrep "yo" >>  car.ip.yo
esconju despescar              ip  | egrep "yo" >>  car.ip.yo
esconju despicar               ip  | egrep "yo" >>  car.ip.yo
esconju despotricar            ip  | egrep "yo" >>  car.ip.yo
esconju desriscar              ip  | egrep "yo" >>  car.ip.yo
esconju destacar               ip  | egrep "yo" >>  car.ip.yo
esconju destocar               ip  | egrep "yo" >>  car.ip.yo
esconju destrincar             ip  | egrep "yo" >>  car.ip.yo
esconju destrocar              ip  | egrep "yo" >>  car.ip.yo
esconju destroncar             ip  | egrep "yo" >>  car.ip.yo
esconju desubicar              ip  | egrep "yo" >>  car.ip.yo
esconju desucar                ip  | egrep "yo" >>  car.ip.yo
esconju desurcar               ip  | egrep "yo" >>  car.ip.yo
esconju desvitrificar          ip  | egrep "yo" >>  car.ip.yo
esconju deszocar               ip  | egrep "yo" >>  car.ip.yo
esconju deszulacar             ip  | egrep "yo" >>  car.ip.yo
esconju diagnosticar           ip  | egrep "yo" >>  car.ip.yo
esconju dignificar             ip  | egrep "yo" >>  car.ip.yo
esconju disecar                ip  | egrep "yo" >>  car.ip.yo
esconju dislocar               ip  | egrep "yo" >>  car.ip.yo
esconju diversificar           ip  | egrep "yo" >>  car.ip.yo
esconju domesticar             ip  | egrep "yo" >>  car.ip.yo
esconju dosificar              ip  | egrep "yo" >>  car.ip.yo
esconju dulcificar             ip  | egrep "yo" >>  car.ip.yo
esconju duplicar               ip  | egrep "yo" >>  car.ip.yo
esconju edificar               ip  | egrep "yo" >>  car.ip.yo
esconju educar                 ip  | egrep "yo" >>  car.ip.yo
esconju ejemplificar           ip  | egrep "yo" >>  car.ip.yo
esconju electrificar           ip  | egrep "yo" >>  car.ip.yo
esconju embarcar               ip  | egrep "yo" >>  car.ip.yo
esconju embarrancar            ip  | egrep "yo" >>  car.ip.yo
esconju embaucar               ip  | egrep "yo" >>  car.ip.yo
esconju embejucar              ip  | egrep "yo" >>  car.ip.yo
esconju embelecar              ip  | egrep "yo" >>  car.ip.yo
esconju embicar                ip  | egrep "yo" >>  car.ip.yo
esconju embizcar               ip  | egrep "yo" >>  car.ip.yo
esconju embocar                ip  | egrep "yo" >>  car.ip.yo
esconju embolicar              ip  | egrep "yo" >>  car.ip.yo
esconju embolsicar             ip  | egrep "yo" >>  car.ip.yo
esconju emborrascar            ip  | egrep "yo" >>  car.ip.yo
esconju emboscar               ip  | egrep "yo" >>  car.ip.yo
esconju emboticar              ip  | egrep "yo" >>  car.ip.yo
esconju embrocar               ip  | egrep "yo" >>  car.ip.yo
esconju empacar                ip  | egrep "yo" >>  car.ip.yo
esconju empalicar              ip  | egrep "yo" >>  car.ip.yo
esconju empañicar              ip  | egrep "yo" >>  car.ip.yo
esconju emporcar               ip  | egrep "yo" >>  car.ip.yo
esconju enarcar                ip  | egrep "yo" >>  car.ip.yo
esconju encalamocar            ip  | egrep "yo" >>  car.ip.yo
esconju encalcar               ip  | egrep "yo" >>  car.ip.yo
esconju encascar               ip  | egrep "yo" >>  car.ip.yo
esconju enchamicar             ip  | egrep "yo" >>  car.ip.yo
esconju encharcar              ip  | egrep "yo" >>  car.ip.yo
esconju enchicar               ip  | egrep "yo" >>  car.ip.yo
esconju enchuecar              ip  | egrep "yo" >>  car.ip.yo
esconju enclocar               ip  | egrep "yo" >>  car.ip.yo
esconju encluecar              ip  | egrep "yo" >>  car.ip.yo
esconju enflacar               ip  | egrep "yo" >>  car.ip.yo
esconju enfocar                ip  | egrep "yo" >>  car.ip.yo
esconju enfoscar               ip  | egrep "yo" >>  car.ip.yo
esconju enfrascar              ip  | egrep "yo" >>  car.ip.yo
esconju engrescar              ip  | egrep "yo" >>  car.ip.yo
esconju enhorcar               ip  | egrep "yo" >>  car.ip.yo
esconju enhuecar               ip  | egrep "yo" >>  car.ip.yo
esconju enjicar                ip  | egrep "yo" >>  car.ip.yo
esconju enjuncar               ip  | egrep "yo" >>  car.ip.yo
esconju enllocar               ip  | egrep "yo" >>  car.ip.yo
esconju enmarcar               ip  | egrep "yo" >>  car.ip.yo
esconju enriscar               ip  | egrep "yo" >>  car.ip.yo
esconju enrocar                ip  | egrep "yo" >>  car.ip.yo
esconju enroscar               ip  | egrep "yo" >>  car.ip.yo
esconju ensacar                ip  | egrep "yo" >>  car.ip.yo
esconju entabicar              ip  | egrep "yo" >>  car.ip.yo
esconju entarascar             ip  | egrep "yo" >>  car.ip.yo
esconju entrechocar            ip  | egrep "yo" >>  car.ip.yo
esconju entrencar              ip  | egrep "yo" >>  car.ip.yo
esconju entresacar             ip  | egrep "yo" >>  car.ip.yo
esconju entroncar              ip  | egrep "yo" >>  car.ip.yo
esconju entunicar              ip  | egrep "yo" >>  car.ip.yo
esconju envarbascar            ip  | egrep "yo" >>  car.ip.yo
esconju enviscar               ip  | egrep "yo" >>  car.ip.yo
esconju enzocar                ip  | egrep "yo" >>  car.ip.yo
esconju equivocar              ip  | egrep "yo" >>  car.ip.yo
esconju erradicar              ip  | egrep "yo" >>  car.ip.yo
esconju esbrencar              ip  | egrep "yo" >>  car.ip.yo
esconju escarificar            ip  | egrep "yo" >>  car.ip.yo
esconju escenificar            ip  | egrep "yo" >>  car.ip.yo
esconju escoscar               ip  | egrep "yo" >>  car.ip.yo
esconju esculcar               ip  | egrep "yo" >>  car.ip.yo
esconju esmantecar             ip  | egrep "yo" >>  car.ip.yo
esconju especificar            ip  | egrep "yo" >>  car.ip.yo
esconju espelucar              ip  | egrep "yo" >>  car.ip.yo
esconju estacar                ip  | egrep "yo" >>  car.ip.yo
esconju estadificar            ip  | egrep "yo" >>  car.ip.yo
esconju estancar               ip  | egrep "yo" >>  car.ip.yo
esconju estatificar            ip  | egrep "yo" >>  car.ip.yo
esconju estipticar             ip  | egrep "yo" >>  car.ip.yo
esconju estratificar           ip  | egrep "yo" >>  car.ip.yo
esconju estucar                ip  | egrep "yo" >>  car.ip.yo
esconju evocar                 ip  | egrep "yo" >>  car.ip.yo
esconju explicar               ip  | egrep "yo" >>  car.ip.yo
esconju fabricar               ip  | egrep "yo" >>  car.ip.yo
esconju falsificar             ip  | egrep "yo" >>  car.ip.yo
esconju fenicar                ip  | egrep "yo" >>  car.ip.yo
esconju fincar                 ip  | egrep "yo" >>  car.ip.yo
esconju fluidificar            ip  | egrep "yo" >>  car.ip.yo
esconju fomicar                ip  | egrep "yo" >>  car.ip.yo
esconju fortificar             ip  | egrep "yo" >>  car.ip.yo
esconju fricar                 ip  | egrep "yo" >>  car.ip.yo
esconju fructificar            ip  | egrep "yo" >>  car.ip.yo
esconju fuñicar                ip  | egrep "yo" >>  car.ip.yo
esconju gasificar              ip  | egrep "yo" >>  car.ip.yo
esconju gelificar              ip  | egrep "yo" >>  car.ip.yo
esconju glorificar             ip  | egrep "yo" >>  car.ip.yo
esconju gratificar             ip  | egrep "yo" >>  car.ip.yo
esconju hamacar                ip  | egrep "yo" >>  car.ip.yo
esconju henificar              ip  | egrep "yo" >>  car.ip.yo
esconju heroificar             ip  | egrep "yo" >>  car.ip.yo
esconju hincar                 ip  | egrep "yo" >>  car.ip.yo
esconju hipotecar              ip  | egrep "yo" >>  car.ip.yo
esconju hocicar                ip  | egrep "yo" >>  car.ip.yo
esconju horcar                 ip  | egrep "yo" >>  car.ip.yo
esconju humidificar            ip  | egrep "yo" >>  car.ip.yo
esconju identificar            ip  | egrep "yo" >>  car.ip.yo
esconju imbricar               ip  | egrep "yo" >>  car.ip.yo
esconju implicar               ip  | egrep "yo" >>  car.ip.yo
esconju imprecar               ip  | egrep "yo" >>  car.ip.yo
esconju impurificar            ip  | egrep "yo" >>  car.ip.yo
esconju incomunicar            ip  | egrep "yo" >>  car.ip.yo
esconju inculcar               ip  | egrep "yo" >>  car.ip.yo
esconju indicar                ip  | egrep "yo" >>  car.ip.yo
esconju intensificar           ip  | egrep "yo" >>  car.ip.yo
esconju intoxicar              ip  | egrep "yo" >>  car.ip.yo
esconju intricar               ip  | egrep "yo" >>  car.ip.yo
esconju intrincar              ip  | egrep "yo" >>  car.ip.yo
esconju invocar                ip  | egrep "yo" >>  car.ip.yo
esconju justificar             ip  | egrep "yo" >>  car.ip.yo
esconju lambiscar              ip  | egrep "yo" >>  car.ip.yo
esconju lamiscar               ip  | egrep "yo" >>  car.ip.yo
esconju lapidificar            ip  | egrep "yo" >>  car.ip.yo
esconju lascar                 ip  | egrep "yo" >>  car.ip.yo
esconju laucar                 ip  | egrep "yo" >>  car.ip.yo
esconju lenificar              ip  | egrep "yo" >>  car.ip.yo
esconju lentificar             ip  | egrep "yo" >>  car.ip.yo
esconju letificar              ip  | egrep "yo" >>  car.ip.yo
esconju lignificar             ip  | egrep "yo" >>  car.ip.yo
esconju lubricar               ip  | egrep "yo" >>  car.ip.yo
esconju lubrificar             ip  | egrep "yo" >>  car.ip.yo
esconju machacar               ip  | egrep "yo" >>  car.ip.yo
esconju machucar               ip  | egrep "yo" >>  car.ip.yo
esconju magnificar             ip  | egrep "yo" >>  car.ip.yo
esconju maleducar              ip  | egrep "yo" >>  car.ip.yo
esconju mancar                 ip  | egrep "yo" >>  car.ip.yo
esconju manducar               ip  | egrep "yo" >>  car.ip.yo
esconju marcar                 ip  | egrep "yo" >>  car.ip.yo
esconju mariscar               ip  | egrep "yo" >>  car.ip.yo
esconju mascar                 ip  | egrep "yo" >>  car.ip.yo
esconju masificar              ip  | egrep "yo" >>  car.ip.yo
esconju masticar               ip  | egrep "yo" >>  car.ip.yo
esconju mechificar             ip  | egrep "yo" >>  car.ip.yo
esconju medicar                ip  | egrep "yo" >>  car.ip.yo
esconju melificar              ip  | egrep "yo" >>  car.ip.yo
esconju mercar                 ip  | egrep "yo" >>  car.ip.yo
esconju metrificar             ip  | egrep "yo" >>  car.ip.yo
esconju mistificar             ip  | egrep "yo" >>  car.ip.yo
esconju mitificar              ip  | egrep "yo" >>  car.ip.yo
esconju mixtificar             ip  | egrep "yo" >>  car.ip.yo
esconju mocar                  ip  | egrep "yo" >>  car.ip.yo
esconju modificar              ip  | egrep "yo" >>  car.ip.yo
esconju molificar              ip  | egrep "yo" >>  car.ip.yo
esconju momificar              ip  | egrep "yo" >>  car.ip.yo
esconju morcar                 ip  | egrep "yo" >>  car.ip.yo
esconju mordicar               ip  | egrep "yo" >>  car.ip.yo
esconju mordiscar              ip  | egrep "yo" >>  car.ip.yo
esconju mortificar             ip  | egrep "yo" >>  car.ip.yo
esconju moscar                 ip  | egrep "yo" >>  car.ip.yo
esconju mullicar               ip  | egrep "yo" >>  car.ip.yo
esconju multiplicar            ip  | egrep "yo" >>  car.ip.yo
esconju mundificar             ip  | egrep "yo" >>  car.ip.yo
esconju neviscar               ip  | egrep "yo" >>  car.ip.yo
esconju nidificar              ip  | egrep "yo" >>  car.ip.yo
esconju nitrificar             ip  | egrep "yo" >>  car.ip.yo
esconju notificar              ip  | egrep "yo" >>  car.ip.yo
esconju obcecar                ip  | egrep "yo" >>  car.ip.yo
esconju ofuscar                ip  | egrep "yo" >>  car.ip.yo
esconju oliscar                ip  | egrep "yo" >>  car.ip.yo
esconju opacar                 ip  | egrep "yo" >>  car.ip.yo
esconju orificar               ip  | egrep "yo" >>  car.ip.yo
esconju osificar               ip  | egrep "yo" >>  car.ip.yo
esconju ozonificar             ip  | egrep "yo" >>  car.ip.yo
esconju pacificar              ip  | egrep "yo" >>  car.ip.yo
esconju panificar              ip  | egrep "yo" >>  car.ip.yo
esconju parificar              ip  | egrep "yo" >>  car.ip.yo
esconju parvificar             ip  | egrep "yo" >>  car.ip.yo
esconju pecar                  ip  | egrep "yo" >>  car.ip.yo
esconju pellizcar              ip  | egrep "yo" >>  car.ip.yo
esconju perjudicar             ip  | egrep "yo" >>  car.ip.yo
esconju personificar           ip  | egrep "yo" >>  car.ip.yo
esconju pescar                 ip  | egrep "yo" >>  car.ip.yo
esconju petrificar             ip  | egrep "yo" >>  car.ip.yo
esconju picar                  ip  | egrep "yo" >>  car.ip.yo
esconju pircar                 ip  | egrep "yo" >>  car.ip.yo
esconju pizcar                 ip  | egrep "yo" >>  car.ip.yo
esconju planificar             ip  | egrep "yo" >>  car.ip.yo
esconju plantificar            ip  | egrep "yo" >>  car.ip.yo
esconju plastificar            ip  | egrep "yo" >>  car.ip.yo
esconju platicar               ip  | egrep "yo" >>  car.ip.yo
esconju polvificar             ip  | egrep "yo" >>  car.ip.yo
esconju pontificar             ip  | egrep "yo" >>  car.ip.yo
esconju practicar              ip  | egrep "yo" >>  car.ip.yo
esconju predicar               ip  | egrep "yo" >>  car.ip.yo
esconju prefabricar            ip  | egrep "yo" >>  car.ip.yo
esconju prevaricar             ip  | egrep "yo" >>  car.ip.yo
esconju pronosticar            ip  | egrep "yo" >>  car.ip.yo
esconju prosificar             ip  | egrep "yo" >>  car.ip.yo
esconju provocar               ip  | egrep "yo" >>  car.ip.yo
esconju publicar               ip  | egrep "yo" >>  car.ip.yo
esconju purificar              ip  | egrep "yo" >>  car.ip.yo
esconju quilificar             ip  | egrep "yo" >>  car.ip.yo
esconju quimificar             ip  | egrep "yo" >>  car.ip.yo
esconju quintuplicar           ip  | egrep "yo" >>  car.ip.yo
esconju radicar                ip  | egrep "yo" >>  car.ip.yo
esconju ramificar              ip  | egrep "yo" >>  car.ip.yo
esconju rarificar              ip  | egrep "yo" >>  car.ip.yo
esconju rascar                 ip  | egrep "yo" >>  car.ip.yo
esconju ratificar              ip  | egrep "yo" >>  car.ip.yo
esconju rebrincar              ip  | egrep "yo" >>  car.ip.yo
esconju rebuscar               ip  | egrep "yo" >>  car.ip.yo
esconju recalcar               ip  | egrep "yo" >>  car.ip.yo
esconju recercar               ip  | egrep "yo" >>  car.ip.yo
esconju reciprocar             ip  | egrep "yo" >>  car.ip.yo
esconju rectificar             ip  | egrep "yo" >>  car.ip.yo
esconju reduplicar             ip  | egrep "yo" >>  car.ip.yo
esconju reedificar             ip  | egrep "yo" >>  car.ip.yo
esconju reeducar               ip  | egrep "yo" >>  car.ip.yo
esconju reembarcar             ip  | egrep "yo" >>  car.ip.yo
esconju refrescar              ip  | egrep "yo" >>  car.ip.yo
esconju reivindicar            ip  | egrep "yo" >>  car.ip.yo
esconju rejacar                ip  | egrep "yo" >>  car.ip.yo
esconju remarcar               ip  | egrep "yo" >>  car.ip.yo
esconju remolcar               ip  | egrep "yo" >>  car.ip.yo
esconju repescar               ip  | egrep "yo" >>  car.ip.yo
esconju repicar                ip  | egrep "yo" >>  car.ip.yo
esconju repizcar               ip  | egrep "yo" >>  car.ip.yo
esconju replicar               ip  | egrep "yo" >>  car.ip.yo
esconju resacar                ip  | egrep "yo" >>  car.ip.yo
esconju resecar                ip  | egrep "yo" >>  car.ip.yo
esconju resinificar            ip  | egrep "yo" >>  car.ip.yo
esconju retacar                ip  | egrep "yo" >>  car.ip.yo
esconju retocar                ip  | egrep "yo" >>  car.ip.yo
esconju retoricar              ip  | egrep "yo" >>  car.ip.yo
esconju retrancar              ip  | egrep "yo" >>  car.ip.yo
esconju retrucar               ip  | egrep "yo" >>  car.ip.yo
esconju reunificar             ip  | egrep "yo" >>  car.ip.yo
esconju revindicar             ip  | egrep "yo" >>  car.ip.yo
esconju revivificar            ip  | egrep "yo" >>  car.ip.yo
esconju revocar                ip  | egrep "yo" >>  car.ip.yo
esconju revolcar               ip  | egrep "yo" >>  car.ip.yo
esconju riscar                 ip  | egrep "yo" >>  car.ip.yo
esconju roncar                 ip  | egrep "yo" >>  car.ip.yo
esconju roscar                 ip  | egrep "yo" >>  car.ip.yo
esconju rubificar              ip  | egrep "yo" >>  car.ip.yo
esconju rubricar               ip  | egrep "yo" >>  car.ip.yo
esconju rucar                  ip  | egrep "yo" >>  car.ip.yo
esconju rusificar              ip  | egrep "yo" >>  car.ip.yo
esconju rusticar               ip  | egrep "yo" >>  car.ip.yo
esconju sacar                  ip  | egrep "yo" >>  car.ip.yo
esconju sacarificar            ip  | egrep "yo" >>  car.ip.yo
esconju sacrificar             ip  | egrep "yo" >>  car.ip.yo
esconju salificar              ip  | egrep "yo" >>  car.ip.yo
esconju salpicar               ip  | egrep "yo" >>  car.ip.yo
esconju sanguificar            ip  | egrep "yo" >>  car.ip.yo
esconju santificar             ip  | egrep "yo" >>  car.ip.yo
esconju saponificar            ip  | egrep "yo" >>  car.ip.yo
esconju secar                  ip  | egrep "yo" >>  car.ip.yo
esconju septuplicar            ip  | egrep "yo" >>  car.ip.yo
esconju sextuplicar            ip  | egrep "yo" >>  car.ip.yo
esconju significar             ip  | egrep "yo" >>  car.ip.yo
esconju simplificar            ip  | egrep "yo" >>  car.ip.yo
esconju sindicar               ip  | egrep "yo" >>  car.ip.yo
esconju sobarcar               ip  | egrep "yo" >>  car.ip.yo
esconju sobreedificar          ip  | egrep "yo" >>  car.ip.yo
esconju sofisticar             ip  | egrep "yo" >>  car.ip.yo
esconju sofocar                ip  | egrep "yo" >>  car.ip.yo
esconju solidificar            ip  | egrep "yo" >>  car.ip.yo
esconju sonsacar               ip  | egrep "yo" >>  car.ip.yo
esconju sopalancar             ip  | egrep "yo" >>  car.ip.yo
esconju sufocar                ip  | egrep "yo" >>  car.ip.yo
esconju suplicar               ip  | egrep "yo" >>  car.ip.yo
esconju surcar                 ip  | egrep "yo" >>  car.ip.yo
esconju tabicar                ip  | egrep "yo" >>  car.ip.yo
esconju tacar                  ip  | egrep "yo" >>  car.ip.yo
esconju tapiscar               ip  | egrep "yo" >>  car.ip.yo
esconju tarascar               ip  | egrep "yo" >>  car.ip.yo
esconju tarrascar              ip  | egrep "yo" >>  car.ip.yo
esconju tascar                 ip  | egrep "yo" >>  car.ip.yo
esconju taucar                 ip  | egrep "yo" >>  car.ip.yo
esconju tecnificar             ip  | egrep "yo" >>  car.ip.yo
esconju testificar             ip  | egrep "yo" >>  car.ip.yo
esconju tincar                 ip  | egrep "yo" >>  car.ip.yo
esconju tipificar              ip  | egrep "yo" >>  car.ip.yo
esconju tocar                  ip  | egrep "yo" >>  car.ip.yo
esconju tonificar              ip  | egrep "yo" >>  car.ip.yo
esconju toxicar                ip  | egrep "yo" >>  car.ip.yo
esconju trabucar               ip  | egrep "yo" >>  car.ip.yo
esconju traficar               ip  | egrep "yo" >>  car.ip.yo
esconju trafulcar              ip  | egrep "yo" >>  car.ip.yo
esconju trancar                ip  | egrep "yo" >>  car.ip.yo
esconju trasbocar              ip  | egrep "yo" >>  car.ip.yo
esconju trastocar              ip  | egrep "yo" >>  car.ip.yo
esconju trastrocar             ip  | egrep "yo" >>  car.ip.yo
esconju trincar                ip  | egrep "yo" >>  car.ip.yo
esconju triplicar              ip  | egrep "yo" >>  car.ip.yo
esconju triscar                ip  | egrep "yo" >>  car.ip.yo
esconju trisecar               ip  | egrep "yo" >>  car.ip.yo
esconju trocar                 ip  | egrep "yo" >>  car.ip.yo
esconju trociscar              ip  | egrep "yo" >>  car.ip.yo
esconju trompicar              ip  | egrep "yo" >>  car.ip.yo
esconju troncar                ip  | egrep "yo" >>  car.ip.yo
esconju trucar                 ip  | egrep "yo" >>  car.ip.yo
esconju truncar                ip  | egrep "yo" >>  car.ip.yo
esconju turificar              ip  | egrep "yo" >>  car.ip.yo
esconju ubicar                 ip  | egrep "yo" >>  car.ip.yo
esconju unificar               ip  | egrep "yo" >>  car.ip.yo
esconju vacar                  ip  | egrep "yo" >>  car.ip.yo
esconju velicar                ip  | egrep "yo" >>  car.ip.yo
esconju ventiscar              ip  | egrep "yo" >>  car.ip.yo
esconju verificar              ip  | egrep "yo" >>  car.ip.yo
esconju versificar             ip  | egrep "yo" >>  car.ip.yo
esconju viaticar               ip  | egrep "yo" >>  car.ip.yo
esconju vindicar               ip  | egrep "yo" >>  car.ip.yo
esconju vitrificar             ip  | egrep "yo" >>  car.ip.yo
esconju vivificar              ip  | egrep "yo" >>  car.ip.yo
esconju volcar                 ip  | egrep "yo" >>  car.ip.yo
esconju zambucar               ip  | egrep "yo" >>  car.ip.yo
esconju zonificar              ip  | egrep "yo" >>  car.ip.yo
esconju zulacar                ip  | egrep "yo" >>  car.ip.yo
esconju zumacar                ip  | egrep "yo" >>  car.ip.yo

